# Generated by Django 3.2.9 on 2021-11-26 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_at', models.DateField(auto_now_add=True, verbose_name='date_at')),
                ('views', models.PositiveIntegerField(verbose_name='views')),
                ('clicks', models.PositiveIntegerField(verbose_name='clicks')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='cost')),
            ],
        ),
    ]
