# Generated by Django 3.2.9 on 2021-11-28 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistics_counter', '0002_alter_activitycollection_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitycollection',
            name='cpc',
            field=models.FloatField(default=12, verbose_name='cpc'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activitycollection',
            name='cpm',
            field=models.FloatField(default=12, verbose_name='cpm'),
            preserve_default=False,
        ),
    ]
