# Generated by Django 3.2.9 on 2021-11-28 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistics_counter', '0003_auto_20211128_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitycollection',
            name='cpc',
            field=models.FloatField(blank=True, null=True, verbose_name='cpc'),
        ),
        migrations.AlterField(
            model_name='activitycollection',
            name='cpm',
            field=models.FloatField(blank=True, null=True, verbose_name='cpm'),
        ),
    ]
